# ! This docker-compose is strictly for development purposes
# ! DO NOT USE IN PROD
 
services:
  backend:
    image: ghcr.io/get-convex/convex-backend:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    volumes:
      - data:/convex/data
    healthcheck:
      test: curl -f http://localhost:3210/version || exit 1
      interval: 5s
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - INSTANCE_NAME=hypershelf
      - INSTANCE_SECRET=0102030405060708090a0b0c0d0e0f100102030405060708090a0b0c0d0e0f10
      - DISABLE_BEACON=true
      - DO_NOT_REQUIRE_SSL=true
      - CONVEX_CLOUD_ORIGIN=http://localhost:3210
      - CONVEX_SITE_ORIGIN=http://localhost:3211
      - DATABASE_URL=postgresql://postgres:donotdeploytoprod@localhost:5432
      - RUST_BACKTRACE=1
      - RUST_LOG=info,common::errors=debug
    network_mode: host

  dashboard:
    image: ghcr.io/get-convex/convex-dashboard:latest
    stop_grace_period: 10s
    stop_signal: SIGINT
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - PUBLIC_CONVEX_BACKEND_URL=http://localhost:3210
    network_mode: host

  postgres:
    image: postgres:17
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: donotdeploytoprod
      POSTGRES_DB: hypershelf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      start_period: 10s
    network_mode: host

  redis:
    image: redis:latest
    command:
      [
        "redis-server",
        "--save",
        "60",
        "1",
        "--loglevel",
        "warning",
        "--requirepass",
        "donotdeploytoprod",
      ]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a donotdeploytoprod ping | grep PONG"]
      interval: 5s
      start_period: 10s
    network_mode: host

volumes:
  data:
  pg_data:
  redis_data:
